spring:
  application:
    name: dc
  thymeleaf:
    cache: false
  security:
    enabled: false
  data:
    mongodb:
      uri: "mongodb://root:aaaaaa@localhost:27017/dc?authSource=admin"
    redis:
      host: localhost
      port: 6379
      database: 0
  messages:
    basename: i18n/messages
  web:
    locale: zh_CN
  mvc:
    async:
      request-timeout: 360000
  servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
  mail:
    host: smtp.example.com
    port: 465
    username: market@example.com
    password: examplepassword
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true  # 如果使用 TLS
      mail.smtp.ssl.enable: true        # 如果使用 SSL
logging:
  level:
    root: INFO
server:
  error:
    path: /dc/pub/error
md5:
  keys:
    password: "adc43D"
    api: "3e4T2"
constant:
  cookie:
    default-max-time: 90
  session:
    non-remember-time: 1
  system:
    admin-user: "a"
    admin-user-password: "a"
  password:
    valid: 0
  login:
    valid: 0
  site-url: "http://localhost:8080"
  ota:
    server: "www.example.com"
    port: 90
    uri: "/dc/web/otadownload"
env:
  production: 0
  test-data: true
tcp:
  port: 7000
  pic-path: "d:\\temp1\\pic"
sim:
  dw:
    api-url: "you don't need it"
    api-id: "you don't need it"
    api-secret: "you don't need it"
